[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "ckanext-spatial"
description = "Geo-related plugins for CKAN"
keywords = [""]
readme = "README.rst"
authors = [
    {name = "Adrià Mercader", email = "amercadero@gmail.com"}
]
maintainers = [
    {name = "CKAN Tech Team and contributors", email = "tech-team@ckan.org"},
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3.9",
]
license = "AGPL-3.0-or-later"
requires-python = ">=3.9"

dynamic = ["version", "dependencies", "optional-dependencies"]

[project.entry-points."ckan.plugins"]
spatial_metadata = "ckanext.spatial.plugin:SpatialMetadata"
spatial_query = "ckanext.spatial.plugin:SpatialQuery"

spatial_harvest_metadata_api = "ckanext.spatial.plugin_harvest_metadata_api:HarvestMetadataApi"

csw_harvester = "ckanext.spatial.harvesters:CSWHarvester"
waf_harvester = "ckanext.spatial.harvesters:WAFHarvester"
doc_harvester = "ckanext.spatial.harvesters:DocHarvester"

# Legacy harvesters
gemini_csw_harvester = "ckanext.spatial.harvesters.gemini:GeminiCswHarvester"
gemini_doc_harvester = "ckanext.spatial.harvesters.gemini:GeminiDocHarvester"
gemini_waf_harvester = "ckanext.spatial.harvesters.gemini:GeminiWafHarvester"


[project.entry-points."ckan.test_plugins"]
test_spatial_plugin = "ckanext.spatial.tests.test_plugin.plugin:TestSpatialPlugin"


[project.urls]
Documentation = "https://docs.ckan.org/projects/ckanext-spatial"
Repository = "https://github.com/ckan/ckanext-spatial"


[tool.setuptools.dynamic]
version = {attr = "ckanext.spatial.__version__"}
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {dev = { file = ["dev-requirements.txt"] }}

