= ISO/TS 19139:2007 resources

== Background

ISO/TS 19139:2007 resources are XML Files provided with the XML
Schema Implementations defined in ISO/TS 19139-2.

Those resources are:

* Catalogues of Codelist, Units of measure (uom) and Coordinate Reference Systems (CRS)
* sample XML

== Change log

=== 2020-03-15

Evert BLEYS on behalf of the ISO/TC 211 XML Maintenance Group

* Update of readme.txt file and schema files
* directory structure brought in line with ISO TC 211 Resolution
* schemaLocation paths adjusted to suit new location
* Reference to ISO 19136 replaced with OGC GML 3.2.1 xml.xsd
  as per ISO / TC 211 Resolution 959

Validation: Schemas have been validated with `<oXygen/>` 2019 Editor 21.1, build 2019120214

=== 2012-07-13

Nicolas Lesage on behalf of the ISO/TC 211 XML Maintenance Group

* Update of Readme.txt file
* Use of absolute schema locations
* Adoption of W3C Implementation of XLink:

Validation: XML Files have been validated with XML Spy 2010 Rel. 2 (MSXML 6.0)
